name: Git Actions to perform pytest on push of a pyton script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.11]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests using pytest
      run: |
        pytest -m component
    - name: Run the black tool
      run: |
        black app_codes
    - name: Run black on test files
      run: |
        black tests
    - name: Run flake8 for linting main codes
      run: |
        flake8 app_codes
    - name: Run flake8 for linting test function codes
      run: |
        flake8 tests
    - name: Run coverage on the unit test cases
      run: |
        coverage run -m pytest  -v -s
    - name: Display coverage report executed by the above step
      run: |
        coverage report -m
  
